-- Generated by nwg-displays on 2026-07-19 at 11:19:38. Do not edit manually.

hl.monitor({
    output = "eDP-1",
    mode = "1920x1080@120.0",
    position = "2320x540",
    scale = 2.0
})
hl.monitor({
    output = "DP-2",
    mode = "1920x1080@60.02",
    position = "400x0",
    scale = 1.0
})
